### ISSUE TITLE
Randomly disconnection 

### ISSUE THREAD

**Issue by DendoD96** [mvalla/openhab-addons#101]
The addon works perfectly for some days and suddenly all things get disconnected. On OpenHAB paper UI i see this error: “
Authentication error. Check gateway password in Thing Configuration Parameters (Handshake failed, invalid response from GW at STEP-2)“.

**Comment by mvalla** [comment]
Which BTicino gateway?
Which openHAB version?
What do you do to resume the situation to a working state?
What does the openHAB log report (see http://<your__openHAB_IP>:9001/) ?

**Comment by DendoD96** [comment]
I have a My Home Screen 10, openhabian with openHAB 2.4. For resume the situation i restart openhabian service (sometimes this doesn't work at first time and i need some extra reboot).  I have filtered the openhab log in order to find 'openwebnet' keyword and i see this:
 [WARN ] [org.openwebnet.bus.MyHomeConnection ] - ##gw-openwebnet-conn## ... STEP-2: HANDSHAKE FAILED response=*#7169706##. The number between *# ## changes every time

**Comment by mvalla** [comment]
It’s very strange that authentication sometimes works and sometimes not. 
To understand better , Set log level to DEBUG (see binding README beta in how to) and extract a complete log from when the problem starts (just before random disconnection) to when it’s solved (with service reload or system reboot).
I think  you can attach the log as text files here?
 Otherwise send me the log via PM on the openHAB community forum)

**Comment by mvalla** [comment]
closing this as not more info/logs was provided
